dev: working, but again, Angular is not showing neither id nor names of items, which are in relationship to the actual displayed entity.
prod:
not working. Shows the errors, that get through in dev-Mode, but seem to make the problems in Angular:

ERROR in src/main/webapp/app/entities/ausdruck/ausdruck-detail.component.html(1,550): : Property 'sprache' does not exist on type 'ISprache'.
src/main/webapp/app/entities/ausdruck/ausdruck-detail.component.html(1,762): : Property 'gruppe' does not exist on type 'IGruppe'.
src/main/webapp/app/entities/bezeichnung/bezeichnung-detail.component.html(1,586): : Property 'sprache' does not exist on type 'ISprache'.
src/main/webapp/app/entities/bezeichnung/bezeichnung-detail.component.html(1,810): : Property 'gruppe' does not exist on type 'IGruppe'.
src/main/webapp/app/entities/wort/wort-detail.component.html(1,506): : Property 'sprache' does not exist on type 'ISprache'.
src/main/webapp/app/entities/wort/wort-detail.component.html(1,702): : Property 'gruppe' does not exist on type 'IGruppe'.